from pydantic import BaseModel
import enum

class LearningStyleType(str, enum.Enum):
    VISUAL = "visual"
    AUDITORY = "auditory"
    READING_WRITING = "reading_writing"
    KINESTHETIC = "kinesthetic"

class LearningStyleResult(BaseModel):
    """VARK assessment outcome"""
    style: LearningStyleType
    description: str  # Generated by Gemini explaining the style


class VARKQuestionSchema(BaseModel):
    question: str
    options: list[str]
